name: Deploy to DigitalOcean Droplet

on:
  push:
    branches:
      - "master"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "22"

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Debug Secrets
        run: |
          echo "DROPLET_IP is set: ${{ secrets.DROPLET_IP != '' }}"
          echo "DROPLET_USER is set: ${{ secrets.DROPLET_USER != '' }}"
          echo "DROPLET_PASSWORD is set: ${{ secrets.DROPLET_PASSWORD != '' }}"

      - name: Deploy to DigitalOcean Droplet
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ secrets.DROPLET_USER }}
          password: ${{ secrets.DROPLET_PASSWORD }}
          script: |
            echo "Connected to Droplet"

            # Install nvm if not installed
            if [ ! -s "$HOME/.nvm/nvm.sh" ]; then
              echo "Installing nvm..."
              curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.0/install.sh | bash
              source ~/.bashrc
            fi
            source ~/.nvm/nvm.sh
            nvm install 22
            nvm use 22

            # Install pnpm globally if not installed
            if ! command -v pnpm &> /dev/null; then
              echo "Installing pnpm globally..."
              npm install -g pnpm
            fi

            # Install pm2 globally if not installed
            if ! command -v pm2 &> /dev/null; then
              echo "Installing pm2 globally..."
              npm install -g pm2
            fi

            # Create app directory if it doesn't exist
            mkdir -p ~/bridget-agent-apis
            cd ~/bridget-agent-apis

            # Write the .env file from a single GitHub secret
            echo "${{ secrets.ENV_FILE }}" > .env

            # Initialize git repository if it doesn't exist
            if [ ! -d .git ]; then
              git init
              git remote add origin https://github.com/KurtVobain/BridgetAI.git
            fi

            # Fetch latest code and handle local changes
            git fetch --all
            git checkout -B master origin/master
            git reset HEAD --hard
            git pull origin master

            echo "Current branch:"
            git branch --show-current
            echo "Git status:"
            git status

            # Install bun globally if not already installed
            if ! command -v bun &> /dev/null; then
              echo "Installing bun globally..."
              sudo curl -fsSL https://bun.sh/install | sudo bash
              sudo ln -s ~/.bun/bin/bun /usr/local/bin/bun
            fi

            # Install pnpm if not already installed
            if ! command -v pnpm &> /dev/null; then
              echo "Installing pnpm globally..."
              npm install -g pnpm
            fi

            # Ensure correct Node.js version again (optional redundancy)
            source ~/.nvm/nvm.sh
            nvm use 22

            # Install dependencies including devDependencies (needed for building)
            pnpm install --prod=false

            # Build the project
            pnpm build

            # Restart the application with PM2 using the ecosystem config
            pm2 restart ecosystem.config.cjs --update-env